################################# Default configuration ###################
baseURL = "test--capro-uio.netlify.app"
title = "CAPRO"
theme = "capro-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
enableGitInfo = true
defaultContentLanguage = "en"
