
################################ Languages ########################
[en]
languageName = "English"
languageCode = "en-us"
weight = 1
home = "Home"
description = "We deal with data processing and capture of big lifescience data for social sciences and humanities."
copyright = "Copyright &copy; 2022 Capro"
[en.banner]
title = "Unlock Your Research Potential"
content = "Whether you're conducting a study or developing a new product, don't let technical skills hold you back. Contact us today to start realizing the true potential of your research project."
image = "images/image-from-rawpixel-id-3337467-jpeg.jpg"
[en.banner.button]
label = "Our Services"
link = "#services"

[en.contact]
title = "Contact Us"
content = "We currently do not have a point of contact. Please check back in soon for updates."

[no]
languageName = "Norsk"
languageCode = "no"
weight = 2
home = "Hjem"
description = "Vi jobber med dataprosessering og fanging av store livsvitenskapsdata for samfunnsvitere og humaniora."
copyright = "Opphavsrett &copy; 2022 Capro"

[no.banner]
title = "Hva kunne prosjektet ditt virkelig utrette"
content = "Ikke sett deg fast i tekniske feller, la oss hjelpe deg!"
image = "images/image-from-rawpixel-id-3337467-jpeg.jpg"
[no.banner.button]
label = "Utforsk oss"
link = "#services"

[no.contact]
title = "Kontakt oss"
content = "Vi har foreløpig ikke noe kontaktpunkt. Kom tilbake senere for mer informasjon."

[no.contact.form]
form_action = "#" #contact form works with https://formspree.io
name = "Ditt navn"
email = "Din e-post"
subject = "Emne"
message = "Beskjed"
submit = "Levér"
