logo: images/logo.png
author: Athanasia Monika Mowinckel
google_analytics_id: ''
post_share: true
preloader:
  enable: false
  preloader: images/logo.png
cookies:
  enable: false
  expire_days: 2
map:
  gmap_api: HUGO_GMAP_API
  map_latitude: '59.943881952368336'
  map_longitude: '10.71344642896635'
  map_marker: images/marker.png
plugins:
  css:
    - link: >-
        https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css
