############################# Default Parameters ##########################
logo = "images/logo.png"
# Meta data
author = "Athanasia Monika Mowinckel"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[preloader]
enable = false
preloader = "images/logo.png"

# cookies
[cookies]
enable = false
expire_days = 2

# google map
[map]
gmap_api = "HUGO_GMAP_API"
map_latitude = "59.943881952368336"
map_longitude = "10.71344642896635"
map_marker = "images/marker.png"


############################# social icons ##########################
#[[social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"



############################# Plugins ##########################
# css plugins
[[plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
