################################# Default configuration ###################
baseURL = "https://www.capro.dev/"
title = "CAPRO"
theme = "capro-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
enableGitInfo = true


############################# Default Parameters ##########################
[params]
logo = "images/logo.svg"
# Meta data
description = "We deal with data processing and capture of big lifescience data for social sciences and humanities."
author = "Athanasia Monika Mowinckel"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.svg"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "59.943881952368336"
map_longitude = "10.71344642896635"
map_marker = "images/marker.png"


################################ Languages ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2022 Capro"

#[Languages.no]
#languageName = "No"
#languageCode = "no"
#weight = 1
#home = "Hjem"
#copyright = "Copyright &copy; 2022 Capro"



################### Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 4

#[[Languages.en.menu.main]]
#name = "pricing"
#url = "#pricing"
#weight = 5

#[[Languages.en.menu.main]]
#name = "blog"
#url = "#blog"
#weight = 6

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7


#[[Languages.en.menu.main]]
#name = "Dropdown"
#weight = 7
#hasChildren = true

#[[Languages.en.menu.main]]
#parent = "Dropdown"
#name = "Dropdown 1"
#url = "#"
#weight = 1

#[[Languages.en.menu.main]]
#parent = "Dropdown"
#name = "Dropdown 2"
#url = "#"
#weight = 2

# Norwegian
[[Languages.no.menu.main]]
name = "om"
url = "#about"
weight = 1

[[Languages.no.menu.main]]
name = "tjenester"
url = "#services"
weight = 2

[[Languages.no.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.no.menu.main]]
name = "team"
url = "#team"
weight = 4

[[Languages.no.menu.main]]
name = "priser"
url = "#pricing"
weight = 5

#[[Languages.no.menu.main]]
#name = "blog"
#url = "#blog"
#weight = 6


############################# social icons ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"



############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Rasa:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"

