
################################ Languages ########################
languageName = "English"
languageCode = "en-us"
weight = 1
home = "Home"
description = "We deal with data processing and capture of big lifescience data for social sciences and humanities."
copyright = "Copyright &copy; 2022 Capro"

[banner]
title = "Unlock Your Research Potential"
content = "Whether you're conducting a study or developing a new product, don't let technical skills hold you back. Contact us today to start realizing the true potential of your research project."
image = "images/image-from-rawpixel-id-3337467-jpeg.jpg"

[banner.button]
label = "Our Services"
link = "#services"

[contact]
title = "Contact Us"
content = "Book a consultation to learn more about what we can offer."

[[contact.item]]
icon = "ti-location-pin" # themify icon pack : https://themify.me/themify-icons
info = "Harald Schjelderups hus, Forskningsveien 3A, 0373 Oslo"
