name: Build site and deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        env:
          HUGO_GMAP_API: ${{ secrets.HUGO_GMAP_API }}
        run: |
          hugo --minify \
            --baseURL https://${{github.event.number}}--capro-uio.netlify.app

      - name: Install netlify cli
        run: npm install netlify-cli -g

      - name: Deploy preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy \
            --dir ./public/ \
            --alias ${{github.event.number}}
        shell: sh

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            The PR has been [deployed as a preview](https://${{github.event.number}}--capro-uio.netlify.app).
            Please double check it looks ok before merging.


