name: Site preview

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - run: sudo apt-get install -y libcurl4-openssl-dev libxml2-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      
      - uses: r-lib/actions/setup-renv@v2

      - name: Get publications
        run: Rscript scripts/get_pubs.R

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Build 🔧
        env:
          HUGO_GMAP_API: ${{ secrets.HUGO_GMAP_API }}
        run: |
          hugo --minify \
            --baseURL https://${{github.event.number}}--capro-uio.netlify.app

      - name: Install netlify cli
        run: npm install netlify-cli -g

      - name: Deploy preview 🚀
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy \
            --dir ./public/ \
            --alias ${{github.event.number}}
        shell: sh

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            The PR has been [deployed as a preview](https://${{github.event.number}}--capro-uio.netlify.app).
            Please double check it looks ok before merging.


