name: Build site and deploy preview

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Enable Pubs Cache
        id: cache-action
        uses: actions/cache@v3
        with:
          path: data/team/pubs/
          key: ${{ runner.os }}-cache-key

      - name: Setup R
        if: steps.cache-action.outputs.cache-hit != 'true'
        uses: r-lib/actions/setup-r@v2

      - if: steps.cache-action.outputs.cache-hit != 'true'
        run: |
          echo "Version: 0.0.9" > DESCRIPTION
          echo "Package: capro-website" >> DESCRIPTION
          echo "Depends: jsonlite, scholar" >> DESCRIPTION
      - name: Install R dependencies
        if: steps.cache-action.outputs.cache-hit != 'true'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Get publications
        if: steps.cache-action.outputs.cache-hit != 'true'
        run: Rscript scripts/get_pubs.R

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build 🔧
        env:
          HUGO_GMAP_API: ${{ secrets.HUGO_GMAP_API }}
        run: |
          hugo --minify \
            --baseURL https://${{github.event.number}}--capro-uio.netlify.app

      - name: Install netlify cli
        run: npm install netlify-cli -g

      - name: Deploy preview 🚀
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy \
            --dir ./public/ \
            --alias ${{github.event.number}}
        shell: sh

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            The PR has been [deployed as a preview](https://${{github.event.number}}--capro-uio.netlify.app).
            Please double check it looks ok before merging.


