name: Update team publications

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '54 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pubs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - run: |
          echo "Version: 0.0.9" > DESCRIPTION
          echo "Package: capro-website" >> DESCRIPTION
          echo "Depends: dplyr, knitr, scholar, here" >> DESCRIPTION
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Get publications
        run: Rscript scripts/get_pubs.R

      - name: Archive pub artifacts
        uses: actions/upload-artifact@v3
        with:
          name: team-pubs
          path: |
            content/team/*/pubs.md



